name: NDK build

env:
  module_id: iforgor
  qmodName: IForgor

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          submodules: true
          lfs: true

      - uses: seanmiddleditch/gha-setup-ninja@v4

      - name: Create ndkpath.txt
        run: echo "$ANDROID_NDK_LATEST_HOME" > ${GITHUB_WORKSPACE}/ndkpath.txt

      - name: Install QPM
        run: |
          wget -q https://github.com/RedBrumbler/QuestPackageManager-Rust/releases/latest/download/qpm-rust-linux -O /usr/local/bin/qpm-rust
          chmod +x /usr/local/bin/qpm-rust
          qpm-rust --version

      - name: QPM Restore
        run: qpm-rust restore

      - name: QPM Collapse
        run: qpm-rust collapse

      - name: Build
        run: qpm-rust s build

      - name: Create Qmod
        run: qpm-rust qmod zip

      - name: Get Library Name
        id: libname
        run: |
          cd ./build/
          pattern="lib${module_id}*.so"
          files=( $pattern )
          echo "NAME=${files[0]}" >> $GITHUB_OUTPUT

      - name: Upload non-debug artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.libname.outputs.NAME }}
          path: ./build/${{ steps.libname.outputs.NAME }}
          if-no-files-found: error

      - name: Upload qmod artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.qmodName}}.qmod
          path: ./${{ env.qmodName }}.qmod
          if-no-files-found: error
